% Add object classes to path
pathdirs = {'gbvs',...
		'data',...
		'preproc',...
		'analyses',...
		'utils',...
		'classes'};

for i = 1:numel(pathdirs)
	addpath(genpath(pathdirs{i}));
end

clear pathdirs
clear i
